version: "3.7"

services:
    db:
        image: postgres
        restart: always
        env_file:
            "./envfile"
        volumes:
            - "./database:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
    
    auth:
        build: 
            context: ./auth
            dockerfile: Dockerfile.prod
        restart: always
        env_file:
            - "./envfile"
        ports:
            - "8084"
            - "8000"

    product-manager:
        build: 
            context: ./product-manager
            dockerfile: Dockerfile.prod
        restart: always
        env_file:
            - "./envfile"
        ports:
            - "8080"
        depends_on:
            - db
            - auth

    product:
        build: 
            context: ./product
            dockerfile: Dockerfile.prod
        restart: always
        env_file:
            - "./envfile"
        ports:
            - "8081"
        depends_on:
            - db

    cart:
        build:
            context: ./cart
            dockerfile: Dockerfile.prod
        restart: always
        env_file:
            - "./envfile"
        ports:
            - "8082"
            - "8001"
        depends_on:
            - db

    checkout:
        build:
            context: ./checkout
            dockerfile: Dockerfile.prod
        restart: always
        env_file:
            - "./envfile"
        ports:
            - "8083"
        depends_on:
            - cart
            - db

    proxy:
        build: ./proxy
        ports:
            - "8080:80"
        depends_on:
            - auth
            - product-manager
            - product
            - cart
            - checkout

